package seng302.managers;

import javafx.scene.Node;
import javafx.scene.layout.AnchorPane;
import javafx.scene.paint.Color;
import seng302.utility.ColourUtils;

import java.io.*;
import java.text.MessageFormat;
import java.util.ArrayList;

/**
 * Created by Jonty on 30-Aug-16.
 */
public class ThemeHandler {

    AnchorPane baseNode;

    String primaryColour, secondaryColour;

    /**
     * Sets window to which attach the developed css.
     *
     * @param node
     */
    public void setBaseNode(AnchorPane node) {
        System.out.println("setBaseNode called: " + node.getChildren().size());
        this.baseNode = node;
        //createCSSFile();

    }

    /**
     * Creates a theme CSS file given a primary and secondary colours, then links the created CSS
     * to a Node (this.baseNode)
     *
     * @param primary
     * @param secondary
     */
    public void setTheme(String primary, String secondary) {

        this.primaryColour = primary;
        this.secondaryColour = secondary;
        generateStyleSheet(primary, secondary);
        setNodeCss(this.baseNode);

    }

    /**
     * Links the created css to a specified node.
     */
    private void setNodeCss(AnchorPane node) {
        if (node != null) {
            node.getStylesheets().clear();
            String filePath = "userstyle.css";
            File f = new File(filePath);
            node.getStylesheets().clear();
            node.getStylesheets().add("file:///" + f.getAbsolutePath().replace("\\", "/"));
            System.out.println("node isn't null and setNodeCss has been done yo!");
        } else {
            System.out.println("node is null??");
        }

    }




    /**
     * Creates the stylesheet for the application to use.
     *
     * @param baseRGB color the user selected
     * @param ldRGB   lighter or darker color generated by the theme
     */
    public void generateStyleSheet(String baseRGB, String ldRGB) {
        this.primaryColour = baseRGB;
        this.secondaryColour = ldRGB;

        ArrayList<String> templateCSS = new ArrayList<String>();

        String line = null;

        try {
            FileReader fileReader =
                    new FileReader(getClass().getResource("/css/templatecss.txt").getFile());

            BufferedReader bufferedReader =
                    new BufferedReader(fileReader);

            while ((line = bufferedReader.readLine()) != null) {
                if (line.contains("{0}{1}")) {
                    templateCSS.add(MessageFormat.format(line, "", ldRGB));
                } else if (line.contains("{0}")) {
                    templateCSS.add(MessageFormat.format(line, baseRGB));
                } else {
                    templateCSS.add(line);
                }
            }

            bufferedReader.close();
        } catch (FileNotFoundException ex) {
            ex.printStackTrace();
        } catch (IOException ex) {
            ex.printStackTrace();
        }

        String fileName = "userstyle.css";

        try {
            FileWriter fileWriter =
                    new FileWriter(fileName);

            BufferedWriter bufferedWriter =
                    new BufferedWriter(fileWriter);

            for (String rule : templateCSS) {
                bufferedWriter.write(rule);
                bufferedWriter.newLine();
            }

            bufferedWriter.close();
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }

    public String getPrimaryColour() {
        return primaryColour;
    }

    public String getSecondaryColour() {
        return secondaryColour;
    }


}
